package com.botofholding.api.Domain.DTO.Response;

/**
 * A generic wrapper to carry both the data and a context-specific success message from the service layer.
 * This allows services to provide detailed feedback for the final API response.
 * @param <T> The type of the data payload.
 * @param data The main data object returned by the service.
 * @param message A detailed success message generated by the service.
 */
public record ServiceResponse<T>(T data, String message) {}